[package]
name = "woodpusher"
version = "0.1.0"
authors = ["Sébastien Willmann <sebastien.willmann@gmail.com>"]

[dependencies]
im = { version = "^15.0.0", features = ["rayon"]}
regex = "^1.1.2"
lazy_static = "^1.3.0"
spectral = "^0.6.0"
rayon = "1.5"
