[package]
name = "woodpusher"
version = "0.1.0"
authors = ["Sébastien Willmann <sebastien.willmann@gmail.com>"]

[dependencies]
im = "^15.0.0"
regex = "^1.1.2"
lazy_static = "^1.3.0"
spectral = "^0.6.0"
